server:
  port: 9301
Spring:
  application:
    name: sq-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:

jwt:
  secret:
  expiration: 604800
  tokenHeader: Authorization
  tokenHead: Bearer

eureka:
  client:
    serviceUrl:
      defaultZone: http://sq-eureka3.local/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@