server:
  port: 9301
Spring:
  application:
    name: sq-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:

eureka:
  client:
    serviceUrl:
      defaultZone:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@