server:
  port: 9301
Spring:
  application:
    name: sq-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-2.cuzbx8vskjop.ap-southeast-2.rds.amazonaws.com:3306/ecommerce?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username:
    password:

jwt:
  secret:
  expiration: 604800
  tokenHeader: Authorization
  tokenHead: Bearer

eureka:
  client:
    serviceUrl:
      defaultZone: http://sq-eureka3.local/eureka/
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    hostname: sq-item.local
    non-secure-port: ${server.port}