version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  backend-deployment:
    docker:
      - image: maven:3.8.4-jdk-11
    steps:
      - checkout
      - run:
          name: "Run backend unit testing"
          command: "mvn test"
      - aws-ecr/build-and-push-image:
          repo: "${ECR_REPO_NAME}"
          tag: "${CIRCLE_SHA1}"

workflows:
  backend-deployment-workflow:
    jobs:
      - backend-deployment:
        jobRef:
          type: approval
          filters:
            branches:
              only: master
