version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  backend-testing:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: "Run backend unit testing"
          command: |
            mvn test \
            -Dspring.profiles.active=test \
            -Dspring.datasource.url=$url \
            -Dspring.datasource.username=$username \
            -Dspring.datasource.password=$password


workflows:
  backend-deployment-workflow:
    jobs:
      - backend-testing:
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          requires:
            - backend-testing
          repo: "${ECR_REPO_NAME}"
          tag: "$(echo $CIRCLE_SHA1 | cut -c -5)"
