version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  backend-testing:
    docker:
      - image: maven:3.8.4-jdk-11
    steps:
      - checkout
      - run:
          name: "Run backend unit testing"
          command: "mvn test"

workflows:
  backend-deployment-workflow:
    jobs:
      - backend-testing:
          type: approval
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          requires:
            - backend-testing
          repo: "${ECR_REPO_NAME}"
          tag: "${CIRCLE_SHA1}"
