pipeline {
    agent: any

    tools: {
        maven
    }

    stages {
        stage('hello world') {
            steps {
                script {
                    echo 'hello world from sq'
                }
            }
        }
    }
}