pipeline {
    agent any

    stages {
        stage('build and test project') {
            steps {
                script {
                    echo 'run mvn install'
                    sh 'chmod 777 ./mvnw'
                    sh './mvnw install'
                }
            }
        }

        stage('build docker images') {
            steps {
                script {
                    echo 'build docker images'
                    sh 'docker-compose build'
                }
            }
        }
    }
}