server:
  port: 5000
  frontendURL: ${frontendURL}
Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    validate-on-migrate: true
  sendgrid:
    api-key: ${sendgridApiKey}

jwt:
  secret: ${jwtSecret}
  tokenHeader: Authorization
  tokenHead: Bearer

paypal:
  client:
    app: ${paypalApp}
    secret: ${paypalSecret}
    mode: sandbox