server:
  port: 5000
Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    validate-on-migrate: true

jwt:
  secret:
  expiration: 604800
  tokenHeader: Authorization
  tokenHead: Bearer

paypal:
  client:
    app:
    secret:
    mode: sandbox