spring:
  profiles:
    active: dev
  application:
    name: demostore

oauth:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}

application:
  cors:
    origins:
      - http://localhost:3000
      - https://store.shuangqiu.blog