server:
  port: 5000
  frontendURL: http://localhost:3000
Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce1?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    validate-on-migrate: true
  sendgrid:
    api-key: ${API_KEY}

jwt:
  secret: mySecret
  expiration: 604800
  tokenHeader: Authorization
  tokenHead: Bearer

paypal:
  client:
    app: AUIIEWLQmECuu7K3qd8xvvBMM7SN76Ql7occ1F0d84RqCpxlI2cchIxe-xBCzSVaxxmFLMSpG-Y1LzkI
    secret: ENlUZyfBghNeZNWtbbvQ0yIdiqZbpnymvWkM2MqpzVpEDiM-jWsKXmgt-FYxCioBJIQgG5zxMqx6VRvE
    mode: sandbox