server:
  port: 9500
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:9400/eureka, http://localhost:9401/eureka
      defaultZone: http://localhost:9400/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: sq-cloud-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: service-user-router
          uri: lb://sq-user
          predicates:
            - Path=/user/**
        - id: service-item-router
          uri: lb://sq-item
          predicates:
            - Path=/item/**
        - id: service-order-router
          uri: lb://sq-order
          predicates:
            - Path=/order/**