server:
  port: 9501
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9400/eureka, http://localhost:9401/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000

spring:
  application:
    name: sq-cloud-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: service-user-router
          uri: lb://sq-user
          predicates:
            - Path=/user/**
        - id: service-item-router
          uri: lb://sq-item
          predicates:
            - Path=/item/**
          filters:
            - name: Hystrix
              args:
                name: HystrixCommand
                fallbackUri: forward:/fallback

        - id: service-order-router
          uri: lb://sq-order
          predicates:
            - Path=/order/user/**
        - id: service-payment-router
          uri: lb://sq-payment
          predicates:
            - Path=/payment/**
        - id: service-management-router
          uri: lb://sq-management
          predicates:
            - Path=/management/**