server:
  port: 80
eureka:
  instance:
    hostname: sq-eureka3.local
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false